name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build and test with Maven
      run: mvn clean verify

    - name: Build Docker image
      run: docker build -t myapp:latest .

# run and name should be at the same level
# also there is tab concept, there should be 2 space gap after run and then each command
    - name: (Optional) Push Docker image
      run:  |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag myapp:latest sopnesh/myapp:latest
        docker push sopnesh/myapp:latest

